### ISSUE TITLE
Mapping all entries from an osm relation type

### ISSUE THREAD

**Issue by Geosynopsis** [omniscale/imposm3#105]
Hello,
Is it possible to import all data for an osm element type (let's say point) in one table using imposm3? 
If it is, what would be a mapping key value pair for it? 
Probably something like,
`type: point`
`mapping:[__any__]`

**Comment by olt** [comment]
This was implemented with 8213d072c139edd63df7f259c861a4bd7b629193
It's `mapping: __any__: [__any__]`. You need to use  the `load_all` option. Check the documentation for that.
