### ISSUE TITLE
Importing Route Relations

### ISSUE THREAD

**Issue by ewestern** [omniscale/imposm3#107]
I'm having trouble importing route relations.
[Here](https://gist.github.com/ewestern/2c6da95a75ef23fab800f378fafc70de) is the mapping I'm using; [here](http://download.geofabrik.de/north-america/us/california.html) is the pbf, and [here](http://www.openstreetmap.org/relation/1244828) is an example of a relation that I am expecting to be imported.

The linestrings indicated in the mapping are imported fine, but both the routes and route_members tables are empty.
Am I missing something?
Thanks

**Comment by ImreSamu** [comment]
>Am I missing something?

Quick fix:  
* add  `load_all: true` to your mapping yml

With   `load_all: true`  your mapping is working for me   ( with hungarian data )

**Comment by ewestern** [comment]
Great, that worked. 
I wonder, though, which tags were necessary for creating the relation tables that weren't getting read into the cache. It seems as though you should be able to create the tables without necessarily reading all of the metadata.

**Comment by ImreSamu** [comment]
> ... without necessarily reading all of the metadata. 

You can manually pre-filter the input data with the [Osmfilter tool](http://wiki.openstreetmap.org/wiki/Osmfilter ).

[ but this method  ( based on my experience)  needs a lot of testing !!  ]

**Comment by olt** [comment]
Normally Imposm caches all tags that are referenced in the mappings and columns, but this is not implemented for relations and relation_members. `load_all` is the right workaround for this at the moment.

**Comment by ewestern** [comment]
Got it. Thanks for the help.
