### ISSUE TITLE
Polygon generalized tables empty for SRID 4326

### ISSUE THREAD

**Issue by rouen-sk** [omniscale/imposm3#114]
I imported OSM extract with Imposm (default mapping.json) with SRID 3857 and 4326 (to different databases of course). With 3857, generalized tables containing polygons (water areas, landuse..) are fine, but when you set 4326, they are just empty.

**Comment by olt** [comment]
The tolerances for simplification are in the unit of the projection. So you need to convert meters to degree.

**Comment by rouen-sk** [comment]
Interesting, didnt think of that. I wonder why it works for linestring generalized tables (roads) with default tolerances?

**Comment by olt** [comment]
Probably because polygons collapse to invalid geometries, while lines are still contains at least to points.

**Comment by rouen-sk** [comment]
OK, so I should change both. One more question - if I am supposed to provide tolerances in degrees, doesnt that mean that the real-world tolerance (in meters for example) will be quite different on equator and closed to the poles? 
Oh, and do I need to adjust also areas in sql_filter to some other units? Thanks!

**Comment by olt** [comment]
Yes and yes (square degrees). Not optimal, but that's how it is right now.
