### ISSUE TITLE
Is there a way to continue processing

### ISSUE THREAD

**Issue by kimmobrunfeldt** [omniscale/imposm3#116]
I was importing planet data to Postgis, and it ran quite a long time until:

```
[Aug 31 05:04:52] [INFO] [PostGIS] Clustering on geometry took: 11h15m29.201990462s
[Aug 31 05:04:52] pq: could not write block 3712763 of temporary file: No space left on device 
```

Is there any way I could continue the processing from this point if I would increase the disk space first? 

*btw for others wondering: 350GB SSD disk was not enough.*

**Comment by olt** [comment]
In this case yes. You are lucky that it stopped during the clustering. This is part of the `-optimize` which you just can repeat (without `-read` and `-write`).

**Comment by kimmobrunfeldt** [comment]
Ok! Thank you for the quick response. 🙇
