### ISSUE TITLE
feature request: repair leveldb databases

### ISSUE THREAD

**Issue by bdon** [omniscale/imposm3#118]
I'm running into an issue where my LevelDB databases are being corrupted. There seems to be a RepairDatabase function in the levigo library so it would make sense to have a command like "imposm3 repaircache -cachedir=/tmp/cache" or so. If you think this is a good idea I can look into implementing it.

**Comment by olt** [comment]
Why not, if it works...

How did you manage to corrupt the DB?

**Comment by bdon** [comment]
I'm not sure - it ran without issues for several months but is now reporting "Corruption: no meta-nextfile entry in descriptor". size of cache directory is 86GB

**Comment by bdon** [comment]
turns out that it was unrecoverable even with repair so I'm not certain if this is effective - closing

**Comment by bdon** [comment]
Actually got this working - success! some more details on failure states: https://docs.basho.com/riak/1.4.7/ops/running/recovery/repairing-leveldb/

It turns out the coords_index database was corrupted - I don't have any insight on how this happened but it was on a large amazon EBS volume.
