### ISSUE TITLE
Error: pq: extra data after last expected column in query COPY 

### ISSUE THREAD

**Issue by vicgarvey** [omniscale/imposm3#121]
I created a customized mapping yml file to import highway data into postgreSQL. When imposm3 tried to write the data from cache at 98.8%, I got the following error: 

`[WARN] [mapping] unhandled type: [Sep 22 21:53:20] [8s] ...... [PostGIS] SQL Error: pq: extra data after last expected column in query COPY "import"."osm_roads" ("osm_id", "geometry", "type", "name", "tunnel", "bridge", "oneway", "ref", "z-order", "access", "service", "class", "maxspeed", "lanes", "surface", "is_in", "source", "attribution") FROM STDIN ([3191805 ...... residential Seymour Street 0 0 0 3 highway <nil> <nil> ])
`

What could be the causes of this issue, and how should I try to resolve it? Thanks!

**Comment by ImreSamu** [comment]
>I created a customized mapping yml 
>...
>What could be the causes of this issue, and how should I try to resolve it? 

Could  you double re-check your `"customized mapping yml"` ?

my suggestion for testing :
* 1. try to find the smallest osm test dataset to replicate this error. 
* 2. remove the last  field definitions from the yml file 
* 3. re-test   with imposm3  ;
* 4. if still error  then GOTO 2.
* 5. if no error -  check the last removed definitions ...  
  * what  was the `**type**:˙  definitions?   
    * Any typo error ?

**Comment by vicgarvey** [comment]
I found the problem: I accidentally capitalized "Name" and "Type" in my mapping yml file. After I change them back to "name" and "type", imposm works...
