### ISSUE TITLE
Unexpected behaviour if "type" is not specified for table

### ISSUE THREAD

**Issue by russss** [omniscale/imposm3#131]
If you accidentally omit the "type" (geometry type) key in your mapping file, you get the postgres error `Invalid type name "(2)"`, as imposm3 tries to execute this command:

`SELECT AddGeometryColumn('import', 'osm_tablename', 'geometry', '3857', '', 2);`

I'd say ideally the mapping file schema should be validated on import to avoid this failing halfway through a long `-import -write` job.

**Comment by olt** [comment]
It is now an error if `type` is not set and it will exit immediately.
