### ISSUE TITLE
OSM and WMS

### ISSUE THREAD

**Issue by aimdev** [omniscale/imposm3#134]
Hi
more of a question really.

I have installed OSM using osm2psql and rendered, took about 60 hours.
The result is the same detail as the online OSM service.

I then installed the same OSM file using imposm3,  took about 13 hours including optimisation.
I then created the WMS service using mapserver, map loading really fast  in comparison to the 
tile based system.

However, the results differ in two ways
1. it doesn't look like the osm2psql result, ie with respect to colours etc.
2. the osm2psql showed the name of my local pub!!, the imposm3 version does not.

I am sure I have goofed somewhere but I cannot find where?

Any assistance would be greatly appreciated

Thanks

Aimee

**Comment by olt** [comment]
Imposm is only a tool to get OSM data into PostgreSQL. The official OSM map uses osm2pgsql and you should use that a well if you want this map design.
