### ISSUE TITLE
Symbol Lookup Error in libgeos_c with version 0.3.0

### ISSUE THREAD

**Issue by russss** [omniscale/imposm3#136]
Using version `0.3.0dev-20161206-e67cf93` on Ubuntu 16.04, I'm getting the following error during the `-write` phase:

    imposm3: symbol lookup error: /usr/local/imposm3/lib/libgeos_c.so.1: undefined symbol: _ZN4geos9operation5valid23TopologyValidationError8toStringEv8%)

This is happening with the planet.pbf file using [this mapping configuration](https://github.com/openinframap/styles/blob/master/mapping.yml). Unfortunately it's happening 36%/5 hours of the way through.

**Comment by russss** [comment]
This may be an issue with the bundled libraries. The imposm3 binary is linking to `libgeos-3.5.0.so`:

	linux-vdso.so.1 =>  (0x00007fff4d91a000)
	libgeos_c.so.1 => /home/russ/imposm3-0.3.0dev-20161206-e67cf93-linux-x86-64/./lib/libgeos_c.so.1 (0x00007f90757ad000)
	libhyperleveldb.so.0 => /home/russ/imposm3-0.3.0dev-20161206-e67cf93-linux-x86-64/./lib/libhyperleveldb.so.0 (0x00007f9075544000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9075319000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9074f50000)
	libgeos-3.5.0.so => /usr/lib/x86_64-linux-gnu/libgeos-3.5.0.so (0x00007f9074bb6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9074833000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f907452a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9074314000)
	/lib64/ld-linux-x86-64.so.2 (0x00005591fa7df000)

But the symlink in the bundled `./lib` is `libgeos-3.5.1.so`. So it uses my OS's `libgeos-3.5.0.so` instead.

I'm not 100% sure this is the cause but I've just started a new `-write` job so I'll know in about 6 hours.

**Comment by olt** [comment]
Thanks for reporting that. It was an error in the build script. There is a new binary with the right GEOS version: https://imposm.org/static/rel/
