### ISSUE TITLE
IMPOSM3_SINGLE_DIFF undocumented and may not shutdown properly.

### ISSUE THREAD

**Issue by AdamGlass** [omniscale/imposm3#151]
## Context

Code contains code that checks environment variable IMPOSM3_SINGLE_DIFF.  If present, the automatic 'run' style diff import mechanism returns after doing a single update.  This functionality is undocumented.   Further, the code 'returns' rather than invoking the shutdown() path which does flush/close which may be a bug.

## Expected Behavior

IMPOSM3_SINGLE_DIFF documented.  Code correctly shuts down after a single diff is processed.

## Actual Behavior

IMPOSM3_SINGLE_DIFF undocumented.  Code appears to not correctly shut down.

## Possible Fix

Change environment variable to command line switch, providing a middle ground between 'diff' and 'run'.  Fix lack of shutdown.

## Steps to Reproduce

Code inspection

## Context

Use automated imposm3 diff application but in a more scriptable way e.g 'it exits when there is nothing to do'  than having to sighup the app after X delay.

## Your Environment

* Version used:
* Environment name and version (e.g. PostgreSQL x.y.z with PostGIS a.b.c):
* Server type and version:
* Operating System and version:

**Comment by olt** [comment]
It's not documented because it is for testing/debugging only. The caches are closed via defer, so I don't think there is a bug in this function. So, I'm closing this.
Please create a new issue if you want to extend the ``run`` command to do more than it does now.
