### ISSUE TITLE
Support region specific replication url, replication interval, and sequence numbering from sources like geofabrik.de

### ISSUE THREAD

**Issue by gregtzar** [omniscale/imposm3#163]
I have created a [pull request](https://github.com/omniscale/imposm3/pull/164) which adds several features and fixes a few bugs:

- The `replicationUrl` parameter written into `last.state.txt` during import was hard coded as `https://planet.openstreetmap.org/replication/minute/` regardless of the data source. I have made it dynamic, based on the `replication_url` specified in the `config.json`. This allows region specific imports from a data source like `geofabrik.de` to output valid `last.state.txt` parameter values that can now be leveraged by a tool like `osmosis` to generate region specific changes lists.
- The `replication_interval` parameter value in the `config.json` is now taken into account when generating the sequence number which is output into the `last.state.txt` file. Before this fix the sequence number was hard coded to be based on a single minute so when performing the `diff` command on an hourly or daily changes list the sequence number would be wrong (usually negative).
- Fixed bug where the `replication_interval` parameter in `config.json` got overwritten by the default flag when no flag is specified (should flags or config.json take priority when both are set?).

Additionally, before the pull request is accepted the following two points should be discussed:

- I want to make sure my handling of the `BaseOptions.DiffStateBefore` parameter in `update:state:state.go:FromPbf()` function won't break anything since I am now calculating it based on the replication interval. It is not clear to me what the purpose of the `BaseOptions.DiffStateBefore` parameter is.
- What is the purpose of the default 2 hour value for `BaseOptions.DiffStateBefore`? In the case of a 24H changes list it is causing the sequence to be off by an entire day. Not a problem I suppose but it just feels sloppy. What problem is having this default value trying to solve?

**Comment by olt** [comment]
Thanks for all you work, but there is already a pull request (#158) that addresses all(?) your changes. :-(

It is still titled WIP, but I it only waits for a final review and merge by me. It would help me if you could review and test this pull request and give it a +1 if everything looks good.
