### ISSUE TITLE
Replace LevelDB with SSD-friendly alternative

### ISSUE THREAD

**Issue by JanJakes** [omniscale/imposm3#167]
LevelDB "was designed specifically for rotating disks" but today SSDs are everywhere. There is a [PR]( https://github.com/omniscale/imposm3/pull/138) with RocksDB support but that might be outdated as well today.

Now there are highly SSD optimized key-value DBs (like https://github.com/dgraph-io/badger, which is written in GO).

Are there any plans to try to replace LevelDB with a more up-to-date alternative? On modern NVMe SSD I see much lower IO throughput than the disk is capable of.

**Comment by olt** [comment]
The next LevelDB version (1.21) contains improvements. The Imposm GitHub releases are already build with this (``LEVELDB_POST_121=1 make``). 

The improvements with RocksDB were mixed (see #138) and alternatives like Badger have other drawbacks. LevelDB is rock stable and fast enough for us. Sure there is always room for improvement, but right now there is no apparent reason for us to spend unpaid time on a replacement.
