### ISSUE TITLE
got errot #include leveldb/c.h,but I have already installed leveldb through cmake

### ISSUE THREAD

**Issue by songrui233** [omniscale/imposm3#169]
Im really confused.Is there somthing I have to link to manually or sth else I have to do？please.

**Comment by songrui233** [comment]
Solved

**Comment by evka2830** [comment]
Hello, please, how was this solved? I have the same issue:
 after:
`go install github.com/omniscale/imposm3/cmd/imposm`
I get:

`# github.com/omniscale/imposm3/vendor/github.com/jmhodges/levigo
src/github.com/omniscale/imposm3/vendor/github.com/jmhodges/levigo/batch.go:4:24: fatal error: leveldb/c.h: No such file or directory
 // #include "leveldb/c.h"
                        ^
compilation terminated.
`

**Comment by jishankai** [comment]
@eva-j Thank you so much! Save my day!

**Comment by helplessJ** [comment]
++ thank you @eva-j   3 years later and still helping.

**Comment by youngqqcn** [comment]
@eva-j  Thansk!
