### ISSUE TITLE
panic: zlib read error: unexpected EOF

### ISSUE THREAD

**Issue by nafis042** [omniscale/imposm3#172]
getting following error when I tried to import data from openstreetmap:

2018/07/10 08:17:20 lowlevel.go:76: zlib read error: unexpected EOF700/s     200/s (84603) W:       0/s       0/s (0) R:      0/s      0/s (0)
panic: zlib read error: unexpected EOF

goroutine 35 [running]:
log.Panic(0xc420181d90, 0x1, 0x1)
        /usr/local/go/src/log/log.go:322 +0xc0
github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7ffd687b7d90, 0x15, 0x1c0a06f, 0x299db6, 0xb0)
        /go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:76 +0xe3
github.com/omniscale/imposm3/parser/pbf.(*Parser).parseBlock(0xc420270320, 0x7ffd687b7d90, 0x15, 0x1c0a06f, 0x299db6)
        /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:89 +0x68
github.com/omniscale/imposm3/parser/pbf.(*Parser).Parse.func1(0xc4202a0720, 0xc420270320)
        /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:56 +0xc8
created by github.com/omniscale/imposm3/parser/pbf.(*Parser).Parse
        /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:65 +0x101

I cant debug and understand the problem. Could anyone tell me why this error occurs

**Comment by olt** [comment]
Please check the checksum of your osm.pbf file. I guess that the file is incomplete.
