### ISSUE TITLE
Add support for multiple types in the same table

### ISSUE THREAD

**Issue by zdila** [omniscale/imposm3#188]
Currently only one `type` can be defined for a table. Sometimes we'd like to use single table for `point`s and `polygons`s. Now we need to duplicate table definition with different name and type.

**Comment by matburnham** [comment]
I'm currently trying to do similar. Although doesn't appear to be documented, `use_single_id_space` seems to be what you're after. See [single_table_mapping.json](https://github.com/omniscale/imposm3/blob/master/test/single_table_mapping.json) for an example.

**Comment by zdila** [comment]
Thanks @matburnham, this should be the solution. Now I am just afraid not to get indo #98. Pity that imposm3 seems to be no more maintained.
