### ISSUE TITLE
MultiPolygon Missing

### ISSUE THREAD

**Issue by Vincent-ThinkGeo** [omniscale/imposm3#209]
## Context

I downloaded this [data](https://download.geofabrik.de/north-america/us/kansas-latest.osm.pbf), then imported it, below was my script:
`{
    "tags": {
        "load_all": true
    },
    "tables": {
        "boundary_county": {
            "columns": [
                {
                    "type": "id",
                    "name": "osm_id",
                    "key": null
                },
                {
                    "type": "geometry",
                    "name": "geometry",
                    "key": null
                }
            ],
            "type": "polygon",
            "filters": {
                "require": {
                    "admin_level": [
                        "6"
                    ]
                }
            },
            "mapping": {
                "boundary": [
                    "administrative"
                ]
            }
        }
    }
}`
One of a record was missing, see [osm](https://www.openstreetmap.org/relation/1070387). I tried to open that pbf file by other applications (QGIS), the record shows correctly.

## Expected Behavior

The polygon shape should be imported correctly.

## Actual Behavior

The shape is missing.

## Possible Fix

This is actually a multipolygon shape, is there something wrong for this shape type ?

## Steps to Reproduce

1. Download  [data](https://download.geofabrik.de/north-america/us/kansas-latest.osm.pbf).
2. Import it using above script.
3. Check the data of [osm](https://www.openstreetmap.org/relation/1070387).
4. Query it by osm_id, it is missing.

## Context

I tried to import some the US data.

## Your Environment

* Version used: imposm-0.8.1-linux-x86-64
* Environment name and version (e.g. PostgreSQL x.y.z with PostGIS a.b.c): PostgreSQL 11.5 with PostGIS 2.5.1
* Server type and version: PostgreSQL 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0, 64-bit
* Operating System and version: Ubuntu 11.5-0ubuntu0.19.04.1

**Comment by ImreSamu** [comment]
imho:  this is an osm data error.
![image](https://user-images.githubusercontent.com/2217320/65831496-766a8e80-e2ba-11e9-8f2b-a40598523b33.png)
the "Sherman Road (198967673)"  is Part of
* Relation "Jefferson County" (1070422) (as outer)
* Relation "Shawnee County" (1070387) (as outer)


https://tools.geofabrik.de/osmi/?view=areas&lon=-95.54854&lat=39.11558&zoom=10

![image](https://user-images.githubusercontent.com/2217320/65831252-f04d4880-e2b7-11e9-87c5-7e91f1f91d01.png)
