### ISSUE TITLE
Regenerate documentation on site

### ISSUE THREAD

**Issue by pnorman** [omniscale/imposm3#216]
https://imposm.org/docs/imposm3/latest/mapping.html does not have all the content on https://github.com/omniscale/imposm3/blob/a7a47ab6b4739125881791794c4cfcdda6a6b913/docs/mapping.rst, specifically the parts about `categorize`, `geojson_intersects` and `geojson_intersects_field`

**Comment by olt** [comment]
Thanks for the reminder.
