### ISSUE TITLE
No Fush of initial small expire tile list

### ISSUE THREAD

**Issue by frodrigo** [omniscale/imposm3#223]
I have trouble with `imposm run` for small updates.

As I understand the code the flush of the tiles list is done in two cases:

* on exist : https://github.com/omniscale/imposm3/blob/master/update/run.go#L93
* after at least 30s of update: https://github.com/omniscale/imposm3/blob/master/update/run.go#L128

So, for small update (>30s) the first flush will be done on next update.

My use case. I import a small extract of Andorra, 2 months old. Then use the `run` command, it update successfully the database quickly, in less than 30s. But no expire tile list is write to disk until I stop the command. I guess it will be written if I wait 24h for the next update, but not tested.

**Comment by francois2metz** [comment]
I had the same issue. What about adding a new configuration option to control this?

**Comment by francois2metz** [comment]
Fixed in https://github.com/omniscale/imposm3/pull/246.
