### ISSUE TITLE
Unification of additional tag keys

### ISSUE THREAD

**Issue by hjanetzek** [omniscale/imposm3#24]
Hi,
is it currently to unify multiple keys into one column? 'mappings' is only for alternative entity classes if I understood correctly. For example there is wild use to tag colors for Simple-3D-Buildings at the moment which would be nice to be put into one column (of course it would be better to clean up the data in OSM):

building:colour (94 662)
building:color (6 926)
colour in combination with building (3000)
color in combination with building (2500)

roof:colour (~150000)
building:roof:colour (~10000)
roof:color (~10000)
building:roof:color (~100)

**Comment by mcm-jyl** [comment]
The other option is to use coalesce in SQL: map both column, use the colour tag if possible, otherwise color. As you said, "of course it would be better to clean up the data in OSM".

**Comment by olt** [comment]
Closing this as it's unlikely that this feature will be supported directly in the future. This could be solved with scripting support. However, there is no time frame for scripting. Right now HStore would be the best solution.
