### ISSUE TITLE
Ocean in mapping.yml

### ISSUE THREAD

**Issue by Shanki1** [omniscale/imposm3#242]
Hi 

i want to style the ocean but the waterareas inside the mapping.yml has no reference and the  "natural": ["water"] does not cover the ocean

only the following type is included:
 reservoir
 basin
 water
 swimming_pool
 riverbank

**Comment by olt** [comment]
There are no ocean areas in OSM. Only the coastlines. You can download oceans here:
https://osmdata.openstreetmap.de/
