### ISSUE TITLE
create tile list for updated regions

### ISSUE THREAD

**Issue by hjanetzek** [omniscale/imposm3#26]
Is it possible to output a list tiles for features that modified by an update? If not, could you suggest a way how this can be implemented?

**Comment by jaakla** [comment]
I'd be also interested

**Comment by TobWen** [comment]
I'd be also interested

**Comment by jaakla** [comment]
Fixed by https://github.com/omniscale/imposm3/pull/127 ?

**Comment by olt** [comment]
Yes, the `-expiretiles-dir` option should cover this.
