### ISSUE TITLE
Wildcards in tag exclusions

### ISSUE THREAD

**Issue by mojodna** [omniscale/imposm3#36]
`osm2pgsql` allows wildcards in the list of tags to drop, e.g. `tiger:*`.  Based on my reading of `mapping/config.go`, there's no equivalent way of defining them here, though it would be nice.  Same syntax would be nice (it's concise), but this could also work (borrowing from `type_mappings`):

``` javascript
{
...
  "exclude": [
    { "tiger": ["__any__"] }
  ]
}
```

**Comment by ImreSamu** [comment]
probably related with: https://github.com/omniscale/imposm3/pull/53 , and *now* solved with this patch https://github.com/omniscale/imposm3/commit/fccaec3977babbe3e8fa063a5071a27563304ab3
 

see  [documentation] ( http://imposm.org/docs/imposm3/latest/mapping.html )   & search for  "tiger:*" 
```json
"tags": {
    "load_all": true,
    "exclude": [
        "created_by",
        "source",
        "tiger:*"                      
    ]
},
```
