### ISSUE TITLE
installation on debian 7 problem 

### ISSUE THREAD

**Issue by bvbever** [omniscale/imposm3#47]
Failed installation on Debian GNU/Linux 7

- Go en the required dependencies are corrected installed.

- The command "go get github.com/omniscale/imposm3" gives te error:
`go get github.com/omniscale/imposm3`
`package github.com/omniscale/imposm3
imports code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path`

How can I fix this ?

**Comment by thomersch** [comment]
There is a small problem that is caused by goprotobuf's transition from Google Code to GitHub. The easiest option would be to get imposm3 via godep. The installation description is given there: https://github.com/omniscale/imposm3#godep

But of course it would be great if someone changed the import path in imposm to the new URL https://github.com/golang/protobuf

**Comment by bvbever** [comment]
Dear thomersch, indeed, with installing imposm3 via godep, imposm3 has been installed !
it would be great it someone changed the import path, as you suggested...

**Comment by thomersch** [comment]
Could it be that you missed the C dependencies? On Debian you have to install the packages `libgeos-dev`, `libprotobuf-dev` and `libleveldb-dev`

**Comment by bvbever** [comment]
when installing those packages:

`godep go install ./...`
`# github.com/jmhodges/levigo`
`could not determine kind of name for C.leveldb_free`
`# github.com/omniscale/imposm3/geom/geos`
`/usr/bin/ld: cannot find -lgeos`
`collect2: error: ld returned 1 exit status`
`godep: go exit status 2`

**Comment by bvbever** [comment]
I fixed the error: 

`/usr/bin/ld: cannot find -lgeos`

`cd /usr/lib`
` sudo ln -s libgeos-3.3.3.so libgeos.so`
` sudo ln -s libgeos-3.3.3.so libgeos.so.1`

The error with C.leveldb_free still remains...

**Comment by bvbever** [comment]
Found some issues on google topics => It sees that you're getting the apt leveldb in addition to building it from source.  The problem I think is with the leveldb from the apt repo. I think it's an old one and you're running into this issue. In the steps remove libleveldb libleveldb-dev libleveldb1 and libsnappy-dev from the apt-get install. Once you just have the 1.15, go get github.com/jmhodges/levigo should work.

normaly : `apt-get install git libleveldb libleveldb-dev libleveldb1 libgeos libsqlite3-0 libsnappy-dev mercurial`
but you have to remove some installations: `apt-get remove libleveldb libleveldb-dev libleveldb1`

Install levelDB yourself:

`wget https://leveldb.googlecode.com/files/leveldb-1.15.0.tar.gz`
`tar -xvf leveldb-1.15.0.tar.gz && cd /leveldb-1.15.0/`
`make`
`cp -r include/leveldb /usr/include/`
`cp libleveldb.* /usr/lib/`

and then use `godep go install ./.. ` (https://github.com/omniscale/imposm3#godep)

everythings works fine !

**Comment by demiurg** [comment]
Might be a more portable way to fix the geos lib problem:
https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/#geos-library-path

**Comment by olt** [comment]
GEOS_LIBRARY_PATH is GeoDjango specific.
