### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by robinhouston** [omniscale/imposm3#50]
Following the installation instructions in the README results in an error:

    $ go get github.com/omniscale/imposm3
    package code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path

This is mentioned in #49, but I thought it ought to be a separate issue.

**Comment by thomersch** [comment]
We have discussed that in https://github.com/omniscale/imposm3/issues/47#issuecomment-100799318, so either you can install it via godep as described in the comment or you use my fork https://github.com/thomersch/imposm3 that contains the bug fix

**Comment by robinhouston** [comment]
Thanks @thomersch! Sorry, I didn’t notice this was essentially a duplicate of #47. I’ll close it.

**Comment by olt** [comment]
Imposm3 now depends on github.com/golang/protobuf instead of code.google.com/p/goprotobuf/proto.
