### ISSUE TITLE
yaml mapping support?

### ISSUE THREAD

**Issue by yohanboniface** [omniscale/imposm3#55]
I personally consider config files are much easier to be written in yaml than in json, so I think supporting yaml for mapping file would be very handy.
If you think it's worth it, I may have a try on it (I don't know go, but that would be certainly simple enough to be a good occasion to hack a bit ;) ).

**Comment by thomersch** [comment]
Although I like the idea of writing yaml instead of json, I don't think it is a particularly great idea to maintain two different systems.

**Comment by yohanboniface** [comment]
I don't know go details, but in general yaml can map to json like structure, so it should only be a matter of having two parsers that ends up to the same structure, no?

**Comment by thomersch** [comment]
It is indeed very easy to map yaml and json onto a struct in Go (yaml would need an additional dependency, but that's a rather minor problem). I just think that it might be a case of unnecessary over-complication for a tool that is supposed to do one thing right.

**Comment by yohanboniface** [comment]
ok ok, let's count my `{` and `}` so ;)

(Closing as there is no call for action, but debate is still possible.)

**Comment by olt** [comment]
Imposm 3 uses JSON because it is supported by Go's stdlib and was easy to integrate. JSON itself is horrible for a configuration format, since it doesn't support comments. I won't mind switching to YAML.

All valid JSON is also valid YAML, so a switch to YAML with the same mapping structure will still read "old" imposm mappings. Question is: does go-yaml support the same mapping?

**Comment by tds4u** [comment]
Hello,
I'm working on a conversion of the OSM CartoCSS style (with YAML). But I've some problems, maybe it's related to import error? Look at the image please.
![imposm_error_roads](https://cloud.githubusercontent.com/assets/5459443/8828410/4ff5fab6-3092-11e5-9900-7c5ad66c71a1.jpg)
Info: Hannover / Bemerode (Germany)

A road should be a LINESTRING and not an area so maybe there is a problem regarding the geometry of many roads or with IMPOSM3?

**Comment by thomersch** [comment]
@tds4u I think you should open a new issue, because I don't see that your post is related to this thread.
