### ISSUE TITLE
Support for routes relations

### ISSUE THREAD

**Issue by yvecai** [omniscale/imposm3#56]
Route relations could be supported as multilinestring.
In Postgis terms, it would be equivalent to a ST_LineMerge().

**Comment by trasch** [comment]
+1

**Comment by trasch** [comment]
Are there any plans on implementing this feature? Or can we speed this up (for a reasonable price)?

**Comment by olt** [comment]
We are not working on this at the moment. 
But Imposm is part of our new [SOSS License](http://omniscale.com/opensource/soss) to help fund features like this. We also implement new features on a contract base if you have a fixed deadline. Just send me an email or private message.

**Comment by orofarne** [comment]
https://github.com/omniscale/imposm3/pull/71

**Comment by olt** [comment]
See #81
