### ISSUE TITLE
Make "optimize" command

### ISSUE THREAD

**Issue by tartakynov** [omniscale/imposm3#60]
If clustering degrades over time, maybe it would be better to take "optimize" step out of import and make it a separate command, so one can optimize a database separately from import

**Comment by olt** [comment]
You can `optimize` existing tables. http://imposm.org/docs/imposm3/latest/tutorial.html#optimize
But be aware that it rewrites all tables. So you should stop importing diffs and expect higher load on the DB server during optimize.
