### ISSUE TITLE
Cryptic Error on reading

### ISSUE THREAD

**Issue by aimdev** [omniscale/imposm3#67]
Following the tutorial I have tried to import pbf files (which work with imposm2) however in each case
i get the following cryptic message

mapping file: invalid character 'g' looking for beginning of value

I am using the example mapping.yml file, and I am running the latest imposm3 on debian jessie.

imposm3-0.1dev-20150515-593f252-linux-x86-64

**Comment by olt** [comment]
Please use the .json mapping. The latest binaries do not support YAML mapping yet.

**Comment by aimdev** [comment]
Hi

Thanks for the reply, looks like itas a no goer on debian jessie.

fatal error: unexpected signal during runtime execution2000) N:    4100/s     100/s (465631) W:       0/s       0/s (0) R:      0/s      0/s (0))
[signal 0x7 code=0x2 addr=0x7f1a1b343000 pc=0x7f1a554b4b8d]

runtime stack:
runtime.gothrow(0x9a8e10, 0x2a)
	/home/os/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/home/os/go/src/runtime/sigpanic_unix.go:14 +0x5e


I suppose I could read on ubunto, write on ubunto , export dbase to jessie?

Will you be supporting debian in the future as it is implied that debian have good gis support.

Thanks

Aimee

**Comment by olt** [comment]
It should work on Jessie. Does is always crash? Can you attach the whole stack trace?

**Comment by aimdev** [comment]
hi

here it is



./imposm3  import -mapping mapping.json -read ../base-build/great-britain-latest.osm.pbf
[Oct  7 08:39:46] [INFO] [reader] reading ../base-build/great-britain-latest.osm.pbf with data till 2015-05-28 21:22:02 +0100 BST
[Oct  7 08:40:46] [INFO] [  1m0s] C:  126000/s (7480000) N:    1600/s (95099) W:       0/s (0) R:      0/s (0)
fatal error: unexpected signal during runtime execution2000) N:    4100/s     100/s (465631) W:       0/s       0/s (0) R:      0/s      0/s (0))
[signal 0x7 code=0x2 addr=0x7f1a1b343000 pc=0x7f1a554b4b8d]

runtime stack:
runtime.gothrow(0x9a8e10, 0x2a)
	/home/os/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/home/os/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 10 [syscall, locked to thread]:
runtime.cgocall_errno(0x405e7d, 0xc208061c30, 0x0)
	/home/os/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208061c10 sp=0xc208061be8
github.com/jmhodges/levigo._Cfunc_leveldb_put(0x2821b30, 0x281fdc0, 0xc209d27de8, 0x8, 0xc208040000, 0x2a, 0xc208061c68)
	github.com/jmhodges/levigo/_obj/_cgo_gotypes.go:370 +0x45 fp=0xc208061c30 sp=0xc208061c10
github.com/jmhodges/levigo.(*DB).Put(0xc208042078, 0xc208042080, 0xc209d27de8, 0x8, 0x8, 0xc208040000, 0x2a, 0x18a, 0x0, 0x0)
	/home/os/imposm/src/github.com/omniscale/imposm3/Godeps/_workspace/src/github.com/jmhodges/levigo/db.go:147 +0xc6 fp=0xc208061c98 sp=0xc208061c30
github.com/omniscale/imposm3/cache.(*DeltaCoordsCache).putCoordsPacked(0xc20800aa80, 0x2e78186, 0xc209c05340, 0x6, 0x1da6, 0x0, 0x0)
	/home/os/imposm/src/github.com/omniscale/imposm3/cache/delta.go:344 +0x227 fp=0xc208061d48 sp=0xc208061c98
github.com/omniscale/imposm3/cache.(*DeltaCoordsCache).PutCoords(0xc20800aa80, 0xc209c02000, 0x1f40, 0x1f40, 0x0, 0x0)
	/home/os/imposm/src/github.com/omniscale/imposm3/cache/delta.go:282 +0x25b fp=0xc208061f08 sp=0xc208061d48
github.com/omniscale/imposm3/reader.func·005()
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:202 +0x28e fp=0xc208061fe0 sp=0xc208061f08
runtime.goexit()
	/home/os/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208061fe8 sp=0xc208061fe0
created by github.com/omniscale/imposm3/reader.ReadPbf
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:206 +0xb8c

goroutine 1 [semacquire, 1 minutes]:
sync.(*WaitGroup).Wait(0xc20800adb0)
	/home/os/go/src/sync/waitgroup.go:132 +0x169
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse(0xc20800ad80)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:51 +0x185
github.com/omniscale/imposm3/reader.ReadPbf(0xc20803f7c0, 0xc208102090, 0xc20803ed80, 0xc2080907e0, 0x0)
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:241 +0xdb4
github.com/omniscale/imposm3/import_.Import()
	/home/os/imposm/src/github.com/omniscale/imposm3/import_/import.go:120 +0xa41
github.com/omniscale/imposm3/cmd.Main(0x9f7428)
	/home/os/imposm/src/github.com/omniscale/imposm3/cmd/main.go:49 +0xce2
main.main()
	/home/os/imposm/src/github.com/omniscale/imposm3/imposm3.go:8 +0x2a

goroutine 5 [select]:
github.com/omniscale/imposm3/logging.(*LogBroker).loop(0xd72e20)
	/home/os/imposm/src/github.com/omniscale/imposm3/logging/logger.go:143 +0x634
created by github.com/omniscale/imposm3/logging.init·1
	/home/os/imposm/src/github.com/omniscale/imposm3/logging/logger.go:240 +0x181

goroutine 7 [select]:
github.com/omniscale/imposm3/stats.(*Statistics).loop(0xc208102090)
	/home/os/imposm/src/github.com/omniscale/imposm3/stats/stats.go:109 +0x1bc
created by github.com/omniscale/imposm3/stats.NewStatsReporter
	/home/os/imposm/src/github.com/omniscale/imposm3/stats/stats.go:88 +0xad

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/home/os/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [chan receive, 1 minutes]:
github.com/omniscale/imposm3/reader.func·003()
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:105 +0xf8
created by github.com/omniscale/imposm3/reader.ReadPbf
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:138 +0x833

goroutine 9 [chan receive, 1 minutes]:
github.com/omniscale/imposm3/reader.func·004()
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:147 +0xf2
created by github.com/omniscale/imposm3/reader.ReadPbf
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:176 +0x9bd

goroutine 11 [chan receive]:
github.com/omniscale/imposm3/reader.func·006()
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:216 +0x12b
created by github.com/omniscale/imposm3/reader.ReadPbf
	/home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:238 +0xd82

goroutine 12 [runnable]:
syscall.Syscall(0x0, 0x17, 0xc20a90aab0, 0xd, 0xd, 0xd, 0x0)
	/home/os/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x17, 0xc20a90aab0, 0xd, 0xd, 0x4142ff, 0x0, 0x0)
	/home/os/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x17, 0xc20a90aab0, 0xd, 0xd, 0x4, 0x0, 0x0)
	/home/os/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208042100, 0xc20a90aab0, 0xd, 0xd, 0x1, 0x0, 0x0)
	/home/os/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc208042100, 0xc20a90aab0, 0xd, 0xd, 0x414d31, 0x0, 0x0)
	/home/os/go/src/os/file.go:95 +0x91
io.ReadAtLeast(0x7f1a55fb6d20, 0xc208042100, 0xc20a90aab0, 0xd, 0xd, 0xd, 0x0, 0x0, 0x0)
	/home/os/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f1a55fb6d20, 0xc208042100, 0xc20a90aab0, 0xd, 0xd, 0xd, 0x0, 0x0)
	/home/os/go/src/io/io.go:316 +0x6d
github.com/omniscale/imposm3/parser/pbf.(*Pbf).nextBlobHeader(0xc2080907e0, 0xc20800ade0)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:194 +0x129
github.com/omniscale/imposm3/parser/pbf.(*Pbf).nextBlock(0xc2080907e0, 0xc20800ade0, 0xc208063fb8, 0x7)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:151 +0x28
github.com/omniscale/imposm3/parser/pbf.func·001()
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:164 +0x45
created by github.com/omniscale/imposm3/parser/pbf.(*Pbf).BlockPositions
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:175 +0x104

goroutine 13 [runnable]:
compress/flate.(*decompressor).moreBits(0xc208a29200, 0x0, 0x0)
	/home/os/go/src/compress/flate/inflate.go:630
compress/flate.(*decompressor).huffSym(0xc208a29200, 0xc208a29230, 0x1, 0x0, 0x0)
	/home/os/go/src/compress/flate/inflate.go:649 +0x5f
compress/flate.(*decompressor).huffmanBlock(0xc208a29200)
	/home/os/go/src/compress/flate/inflate.go:406 +0x41
compress/flate.(*decompressor).Read(0xc208a29200, 0xc208898000, 0x98e1, 0x98e1, 0x8000, 0x0, 0x0)
	/home/os/go/src/compress/flate/inflate.go:286 +0x1cc
compress/zlib.(*reader).Read(0xc2080c6aa0, 0xc208898000, 0x98e1, 0x98e1, 0x8000, 0x0, 0x0)
	/home/os/go/src/compress/zlib/reader.go:95 +0xf0
io.ReadAtLeast(0x7f1a55fbba98, 0xc2080c6aa0, 0xc208888000, 0x198e1, 0x198e1, 0x198e1, 0x10000, 0x0, 0x0)
	/home/os/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f1a55fbba98, 0xc2080c6aa0, 0xc208888000, 0x198e1, 0x198e1, 0x198e1, 0x0, 0x0)
	/home/os/go/src/io/io.go:316 +0x6d
github.com/omniscale/imposm3/parser/pbf.readBlobData(0x7ffd713df842, 0x2a, 0xf2fe4e7, 0xc702, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:65 +0x8cf
github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7ffd713df842, 0x2a, 0xf2fe4e7, 0xc702, 0xc20807ba00)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:74 +0x3e
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc20800ad80, 0x7ffd713df842, 0x2a, 0xf2fe4e7, 0xc702)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:86 +0x41
github.com/omniscale/imposm3/parser/pbf.func·002()
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xa3
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x137

goroutine 14 [runnable]:
compress/flate.(*decompressor).huffSym(0xc208260000, 0xc208260030, 0xa0, 0x0, 0x0)
	/home/os/go/src/compress/flate/inflate.go:645
compress/flate.(*decompressor).huffmanBlock(0xc208260000)
	/home/os/go/src/compress/flate/inflate.go:406 +0x41
compress/flate.(*decompressor).nextBlock(0xc208260000)
	/home/os/go/src/compress/flate/inflate.go:269 +0x26e
compress/flate.(*decompressor).Read(0xc208260000, 0xc209b8e000, 0x9893, 0x9893, 0x8000, 0x0, 0x0)
	/home/os/go/src/compress/flate/inflate.go:286 +0x1cc
compress/zlib.(*reader).Read(0xc208224050, 0xc209b8e000, 0x9893, 0x9893, 0x8000, 0x0, 0x0)
	/home/os/go/src/compress/zlib/reader.go:95 +0xf0
io.ReadAtLeast(0x7f1a55fbba98, 0xc208224050, 0xc209b7e000, 0x19893, 0x19893, 0x19893, 0x10000, 0x0, 0x0)
	/home/os/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f1a55fbba98, 0xc208224050, 0xc209b7e000, 0x19893, 0x19893, 0x19893, 0x0, 0x0)
	/home/os/go/src/io/io.go:316 +0x6d
github.com/omniscale/imposm3/parser/pbf.readBlobData(0x7ffd713df842, 0x2a, 0xf30abfa, 0xc6f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:65 +0x8cf
github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7ffd713df842, 0x2a, 0xf30abfa, 0xc6f0, 0xc2084f3400)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:74 +0x3e
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc20800ad80, 0x7ffd713df842, 0x2a, 0xf30abfa, 0xc6f0)
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:86 +0x41
github.com/omniscale/imposm3/parser/pbf.func·002()
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xa3
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x137

goroutine 15 [chan receive]:
github.com/omniscale/imposm3/parser/pbf.func·002()
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:39 +0x5f
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x137

goroutine 16 [chan receive]:
github.com/omniscale/imposm3/parser/pbf.func·002()
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:39 +0x5f
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x137

**Comment by aimdev** [comment]
Hi

Hands up, in embarrassment, it may be due to the /tmp being too small.

Just read in a couple of smaller pbf’s ok, time to boot up gparted!!

Aimee

**Comment by olt** [comment]
Great. You can change the -cachedir if you have free space in another partition.

**Comment by aimdev** [comment]
Hi

yes, found it!!. A question, can imposm3 use cachefiles generated by imposm2 (haveing loaded in most of the world yesterday!!)

Thanks

Aimee

**Comment by olt** [comment]
No, they are completely different.

**Comment by aimdev** [comment]
Hi

ok, thanks for all your help

Aimee
