### ISSUE TITLE
Remove table prefixes

### ISSUE THREAD

**Issue by flemmens** [omniscale/imposm3#73]
I did not find any way to remove table prefixes. I can change the prefix in the connection string:
 "connection": "postgis://postgres:pwd@localhost/postgres?prefix=abc"

But if I remove the prefix option or if I specify a null value like this
 "connection": "postgis://postgres:pwd@localhost/postgres?prefix="

My tables have still the default osm_ prefix. How is it possible to remove this prefix ?

**Comment by ImreSamu** [comment]
just a tipp :  try     ?prefix=NONE
( https://github.com/omniscale/imposm3/blob/master/database/postgis/util.go#L49 )

**Comment by olt** [comment]
I've added this to the docs: http://imposm.org/docs/imposm3/latest/tutorial.html#writing

**Comment by flemmens** [comment]
Great, thanks!
