### ISSUE TITLE
packaging binary release

### ISSUE THREAD

**Issue by bdon** [omniscale/imposm3#75]
Hi, I've been using the standalone binaries like http://imposm.org/static/rel/ which are very convenient - 
What are the steps for building the package ourselves?

**Comment by olt** [comment]
The actual build script is part of our internal build configuration. I need to extract that sometime. 

But, it's basically just `make build`.

If you look at the Makefile, you will see that it sets the rpath to `${ORIGIN}/lib` which is a `lib` dir relative to the Imposm3 resulting binary. Linux will look into that dir first when it loads a linked library.

Then you need to copy `lib(hyper)leveldb` and `libgeos` files to the `lib` dir.
You will also need to update libgeos_c to find the right libgeos library:

    chrpath libgeos_c.so -r '${ORIGIN}'

**Comment by bdon** [comment]
Thanks - I had to also make this change
```
-#cgo LDFLAGS: -lgeos_c -lgeos
 +#cgo LDFLAGS: -lgeos_c
```
To get it to compile on trusty with package libgeos-dev from ubuntu universe - should this be necessary?

**Comment by bdon** [comment]
Nevermind i see this is already referred to by #70 - closing
