### ISSUE TITLE
Why does Imposm need a state file to import a diff ?

### ISSUE THREAD

**Issue by Gustry** [omniscale/imposm3#79]
I'm playing with Imposm3 and I would like to know why there is a warning in the console when I import a osc.gz into my postgis database.

I can read : 
`[WARN] [diff] cannot find state file /home/import_queue/2015-12-21T21:30:34Z.state.txt`

I though that Imposm doesn't need to know the state file.

Thanks

**Comment by olt** [comment]
It doesn't _need_ to. I've updated the documentation to describe the state.txt handling.

**Comment by Gustry** [comment]
Ok, thanks for the explanation.
