### ISSUE TITLE
Support for dumping all nodes, ways or relations to a table

### ISSUE THREAD

**Issue by jocelynj** [omniscale/imposm3#80]
Hi,

I'm investigating if imposm3 might be faster than osmosis to dump a medium-sized PBF file, with a pgsnapshot schema. I think the only missing feature would be to dump all nodes, ways or relations, without looking at a tag mapping.

Is it possible? I couldn't find anything in the documentation, and the code doesn't seem to allow this.

Thanks.

**Comment by olt** [comment]
No, it's not possible to insert nodes, ways or relations if they don't have any tags.
